### ISSUE TITLE
Cannot build gstreamer1.0-plugins-imx / PXP support

### ISSUE THREAD

**Issue by QB4-dev** [SoMLabs/meta-somlabs#3]
When I try to add `gstreamer1.0-plugins-imx` to my image bitbake returns following erorr message:
```
ERROR: Nothing PROVIDES 'gstreamer1.0-plugins-imx'
gstreamer1.0-plugins-imx was skipped: incompatible with machine visionsom6ull (not in COMPATIBLE_MACHINE)
```
`visionsom6ull ` is not  on `COMPATIBLE_MACHINE = "(mx6dl|mx6q|mx6sl|mx6sx|mx6ul|mx6ull|mx7d)"`

in recipe:

https://github.com/Freescale/meta-freescale/blob/warrior/recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_git.bb

but in machine conf there is `mx6ull`
`MACHINEOVERRIDES =. "mx6:mx6ull:use-mainline-bsp:"`

Also is this node in device-tree enough to support PXP on iMX6ULL?
```
pxp_v4l2 {
		compatible = "fsl,imx6ul-pxp-v4l2", "fsl,imx6sx-pxp-v4l2", "fsl,imx6sl-pxp-v4l2";
		status = "okay";
	};
```
https://github.com/SoMLabs/meta-somlabs/blob/warrior/recipes-kernel/linux/linux-fslc/somlabs-visionsom-6ull.dts#L76

There was pxp node in older kernels
https://github.com/Freescale/linux-fslc/blob/4.1-2.0.x-imx/arch/arm/boot/dts/imx6ul.dtsi#L1072
but it's missing in new Linux-fslc versions
https://github.com/Freescale/linux-fslc/blob/5.1.x+fslc/arch/arm/boot/dts/imx6ul.dtsi

**Comment by voloviq** [comment]
Please check "gstreamer1.0-plugins-imx" now. In my host it compiles, but I now check it if works.
Regards

**Comment by QB4-dev** [comment]
@voloviq 
Thank you, now `gstreamer1.0-plugins-imx` compiles without problems. 
I'm still not sure if PXP is enabled in new linux kernels. As I mentioned in previous message: 
The only thing related to pxp is this fragment of device tree:
```
pxp_v4l2 {
		compatible = "fsl,imx6ul-pxp-v4l2", "fsl,imx6sx-pxp-v4l2", "fsl,imx6sl-pxp-v4l2";
		status = "okay";
	};
```
Someone removed pxp node from **/arch/arm/boot/dts/imx6ul.dtsi**
Kernel won't build if this part of device tree is uncommented:
```
&pxp {
	status = "okay";
};
```
Should I add it manually like in this patch?
https://patchwork.kernel.org/patch/10590107/

**Comment by voloviq** [comment]
I added the merged mentioned pxp patch. Uncommnetd pxp in dts. Please check if pxp works now.
Regards

**Comment by voloviq** [comment]
I think the issue can be closed.
